Update workflow.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,10 +1,10 @@
 name: Release on PR Merge
 
-on: deployment
+on: push
 
 jobs:
   release-and-bump-version:
-    if: github.event.deployment.environment == 'production'
+    # if: github.event.deployment.environment == 'production'
     runs-on: ubuntu-latest
     env:
       GITHUB_TOKEN: '${{ secrets.GAUGEBOT_GITHUB_TOKEN }}'
@@ -29,44 +29,45 @@ jobs:
           git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
           git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
 
-      - name: Deploy on github
-        run: |
-          version=$(grep '"version"' package.json | sed 's/"version":[[:space:]]*"//' | sed 's/",//' | tr -d [:space:])
-          if [ -z "$version" ]; then
-              echo "Taiko version is not set"
-              exit 1
-          fi
-          echo -e "taiko v$version\n\n" > desc.txt
-          release_description=$(ruby -e "$(curl -sSfL https://github.com/getgauge/gauge/raw/master/build/create_release_text.rb)" getgauge taiko)
-          echo "$release_description" >> desc.txt
-          echo "Creating new draft for release v$version"
-          hub release create -F ./desc.txt "v$version"
-          rm -rf desc.txt
+      # - name: Deploy on github
+      #   run: |
+      #     version=$(grep '"version"' package.json | sed 's/"version":[[:space:]]*"//' | sed 's/",//' | tr -d [:space:])
+      #     if [ -z "$version" ]; then
+      #         echo "Taiko version is not set"
+      #         exit 1
+      #     fi
+      #     echo -e "taiko v$version\n\n" > desc.txt
+      #     release_description=$(ruby -e "$(curl -sSfL https://github.com/getgauge/gauge/raw/master/build/create_release_text.rb)" getgauge taiko)
+      #     echo "$release_description" >> desc.txt
+      #     echo "Creating new draft for release v$version"
+      #     hub release create -F ./desc.txt "v$version"
+      #     rm -rf desc.txt
 
-      - name: 'deployment success'
-        if: success()
-        uses: 'deliverybot/status@master'
-        with:
-          state: 'success'
-          token: '${{ secrets.GITHUB_TOKEN }}'
+      # - name: 'deployment success'
+      #   if: success()
+      #   uses: 'deliverybot/status@master'
+      #   with:
+      #     state: 'success'
+      #     token: '${{ secrets.GITHUB_TOKEN }}'
 
-      - name: 'deployment failure'
-        if: failure()
-        uses: 'deliverybot/status@master'
-        with:
-          state: 'failure'
-          token: '${{ secrets.GITHUB_TOKEN }}'
+      # - name: 'deployment failure'
+      #   if: failure()
+      #   uses: 'deliverybot/status@master'
+      #   with:
+      #     state: 'failure'
+      #     token: '${{ secrets.GITHUB_TOKEN }}'
 
-      - name: Deploy npm
-        env:
-          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
-        run: |
-          echo "It will publish the taiko."
-          # npm publish --access=public
+      # - name: Deploy npm
+      #   env:
+      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+      #   run: |
+      #     echo "It will publish the taiko."
+      #     # npm publish --access=public
 
       - name: Bump up version
         run: |
           git checkout master && git checkout . && git pull --rebase
           version=$(npm version patch --no-git-tag-version)
+          git checkout -b "v$version"
           git commit -am "Bumping up -> $version"
-          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" master
+          hub pull-request -p -m "Bump up version further development."
